### ISSUE TITLE
Serialization does not work properly

### ISSUE THREAD

**Issue by b-squared42** [MateriiApps/partial-kt#2]
It seems like serialization does not work when using Retrofit.

I have a data class called PrivateUser, like this:
```kotlin
@Partialize
    data class PrivateUser(
        override val id: String = "",
        override val nickname: String = "",
        override val avatarUrl: String? = null,
        override val name: String = "",
        override val email: String = "",
        override val syncAvatarWithGoogle: Boolean = true,
        override val registrationDate: Timestamp = Timestamp.now(),
        override val isOnboarded: Boolean = false,
    ) : User
```

When I call a method using Retrofit with the Partial as an parameter, like this:
```kotlin
// method:
@PATCH("user") fun updateUser(@Body user: PrivateUserPartial): Call<Void>

// method-call:
foobar.update(
    PrivateUserPartial(
        name = Partial.Value(fullName),
        nickname = Partial.Value(nickName),
        isOnboarded = Partial.Value(true)
    )
).execute()
```
...the Server gets the following Body:
```json
{"avatarUrl":{},"email":{},"id":{},"isOnboarded":{},"name":{},"nickname":{},"registrationDate":{},"syncAvatarWithGoogle":{}}
```
..which is obviously not understandably on the server side.

Is it a mistake on my end or can you adapt the serialization?

**Comment by rushiiMachine** [comment]
This library was designed for use with [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) in mind, and as such the serializer/deserializers necessary are only implemented for it. I'm not familiar with retrofit, but if it supports polymorphic (de)serialization you could reimplement them similar to how they are [here](https://github.com/MateriiApps/partial-kt/blob/67145a8bdefdc9e77441427efd75882ca4af5eae/partial/src/main/kotlin/com/github/materiiapps/partial/PartialSerializer.kt).
